back/urls.py
from django.urls import path
import back.views

app_name = 'back'

urlpatterns = [
    path('fetch_record/post/', back.views.api_data),
    path('', back.views.back_index, name='back_index'),
    path('retry/<int:r_id>', back.views.retry_index, name='back_retry'),
    path('retry/process/<int:r_id>', back.views.retry_process, name='back_retry_process')
]

fetch_backend/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('back/', include('back.urls'))
]

back/models.py
from django.db import models

# Create your models here.


class FetchRecord(models.Model):
    ip = models.CharField(max_length=64)
    group = models.CharField(max_length=64)
    file_date = models.CharField(max_length=64)
    src_file_name = models.CharField(max_length=128)
    src_file_dir = models.CharField(max_length=128)
    src_file_path = models.CharField(max_length=128)
    dest_file_dir = models.CharField(max_length=128)
    dest_file_path = models.CharField(max_length=128)
    status = models.IntegerField()
    error_msg = models.CharField(max_length=1024)
    playbook_name = models.CharField(max_length=64)
    create_time = models.DateTimeField(auto_now_add=True)
    modify_time = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'fetch_record'

back/views.py
import threading
from django.shortcuts import render, redirect, reverse
from back.models import FetchRecord
from django.http.response import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods
from ansible_scripts.fetch_log import run
# Create your views here.


def back_index(request):
    all_records = FetchRecord.objects.all().order_by('-create_time')
    return render(request, 'back/index.html', context={'records': all_records})


def retry_index(request, r_id):
    record = FetchRecord.objects.get(pk=r_id)
    return render(request, 'back/retry.html', context={'record': record})


def retry_process(request, r_id):
    ip = request.POST.get('ip')
    group = request.POST.get('group')
    file_date = request.POST.get('file_date')
    src_file_name = request.POST.get('src_file_name')
    src_file_dir = request.POST.get('src_file_dir')
    dest_file_dir = request.POST.get('dest_file_dir')
    playbook_name = request.POST.get('playbook_name')
    cfg = {
        "src_file_dir": src_file_dir,
        "dest_file_dir": dest_file_dir,
        "playbook_name": playbook_name
    }
    fr = FetchRecord.objects.get(pk=r_id)
    fr.status = 2
    fr.save()
    t = threading.Thread(target=run, args=(ip, group, cfg, src_file_name, file_date, r_id))
    t.start()
    return redirect(reverse('back:back_index'))


@require_http_methods('POST')
@csrf_exempt
def api_data(request):
    ip = request.POST.get('ip')
    group = request.POST.get('group')
    file_date = request.POST.get('file_date')
    src_file_name = request.POST.get('src_file_name')
    src_file_dir = request.POST.get('src_file_dir')
    src_file_path = request.POST.get('src_file_path')
    dest_file_dir = request.POST.get('dest_file_dir')
    dest_file_path = request.POST.get('dest_file_path')
    status = request.POST.get('status')
    error_msg = request.POST.get('error_msg')
    playbook_name = request.POST.get('playbook_name')
    r_id = request.POST.get('r_id')
    if r_id == '-1':
        fr = FetchRecord(
            ip=ip,
            group=group,
            file_date=file_date,
            src_file_name=src_file_name,
            src_file_dir=src_file_dir,
            src_file_path=src_file_path,
            dest_file_dir=dest_file_dir,
            dest_file_path=dest_file_path,
            status=status,
            error_msg=error_msg,
            playbook_name=playbook_name
        )
        fr.save()
    else:
        fr = FetchRecord.objects.get(pk=r_id)
        fr.ip = ip
        fr.group = group
        fr.file_date = file_date
        fr.src_file_name = src_file_name
        fr.src_file_dir = src_file_dir
        fr.src_file_path = src_file_path
        fr.dest_file_dir = dest_file_dir
        fr.dest_file_path = dest_file_path
        fr.status = status
        fr.error_msg = error_msg
        fr.playbook_name = playbook_name
        fr.save()
    return HttpResponse('ok')

templates/back/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/popper.js/1.15.0/umd/popper.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <style>
        .table td, .table th {
            vertical-align: middle;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'back:back_index' %}">Home</a>
        </li>
      </ul>
    </nav>
    <br>
    <div class="contain">
  <h2>Records</h2>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>ip</th>
        <th>群组</th>
        <th>文件时间</th>
        <th>源文件名称</th>
        <th>源文件所在目录</th>
        <th>源文件全路径</th>
        <th>目标目录</th>
        <th>目标全路径</th>
        <th>状态</th>
        <th>错误信息</th>
        <th style="width: 40px">创建时间</th>
        <th>操作</th>
      </tr>
    </thead>
    <tbody>
        {% for record in records %}
            {% if record.status == 0 %}
                <tr class="table-success">
            {% elif record.status == -1 %}
                <tr class="table-danger">
            {% elif record.status == 1 %}
                <tr class="table-warning">
            {% elif record.status == 2 %}
                <tr class="table-primary">
            {% endif %}
                <td>{{ record.ip }}</td>
                <td>{{ record.group }}</td>
                <td>{{ record.file_date }}</td>
                <td>{{ record.src_file_name }}</td>
                <td>{{ record.src_file_dir }}</td>
                <td>{{ record.src_file_path }}</td>
                <td>{{ record.dest_file_dir }}</td>
                <td>{{ record.dest_file_path }}</td>
                {% if record.status == 0 %}
                    <td><span class="badge badge-success">成功</span></td>
                {% elif record.status == -1 %}
                    <td><span class="badge badge-danger">失败</span></td>
                {% elif record.status == 1 %}
                    <td><span class="badge badge-warning">无法连接</span></td>
                {% elif record.status == 2 %}
                    <td><span class="badge badge-primary">重试中</span></td>
                {% endif %}
                {% if record.status != 0 %}
                    <td><a href="#" data-toggle="tooltip" data-placement="top" title="{{ record.error_msg }}">{{ record.error_msg|slice:":10" }}...</a></td>
                {% else %}
                    <td></td>
                {% endif %}
                <td>{{ record.create_time|date:"Y-m-d H:i:s" }}</td>
                {% if record.status != 0 %}
                    <td><a class="btn btn-info" href="{% url 'back:back_retry' record.id %}" role="button">Retry</a></td>
                {% else %}
                    <td></td>
                {% endif %}
            </tr>

        {% endfor %}

    </tbody>
  </table>
</div>
<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
});
</script>
</body>
</html>

templates/back/retry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/popper.js/1.15.0/umd/popper.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <style>
        .contain {
            width: 30%;
            margin-left: 500px;
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <div class="contain">
        <form action="{% url 'back:back_retry_process' record.id %}" method="post">
            {% csrf_token %}
          <div class="form-group">
            <label for="ip">ip</label>
            <input type="text" class="form-control" name="ip" id="ip" value="{{ record.ip }}">
          </div>
          <div class="form-group">
            <label for="group">群组</label>
            <input type="text" class="form-control" name="group" id="group" value="{{ record.group }}">
          </div>
          <div class="form-group">
            <label for="file_date">文件时间</label>
            <input type="text" class="form-control" name="file_date" id="file_date" value="{{ record.file_date }}">
            <small class="form-text text-muted">比如2020-01-02</small>
          </div>
          <div class="form-group">
            <label for="src_file_name">源文件名</label>
            <input type="text" class="form-control" name="src_file_name" id="src_file_name" value="{{ record.src_file_name }}">
          </div>
          <div class="form-group">
            <label for="src_file_dir">源文件目录</label>
            <input type="text" class="form-control" name="src_file_dir" id="src_file_dir" value="{{ record.src_file_dir }}">
          </div>
          <div class="form-group">
            <label for="dest_file_dir">目标目录</label>
            <input type="text" class="form-control" name="dest_file_dir" id="dest_file_dir" value="{{ record.dest_file_dir }}">
          </div>
          <div class="form-group">
            <label for="playbook_name">playbook名称</label>
            <input type="text" class="form-control" name="playbook_name" id="playbook_name" value="{{ record.playbook_name }}">
          </div>
          <button type="submit" class="btn btn-primary">Retry</button>
        </form>
    </div>

</body>
</html>